%% Description: 
% This function re-builds the vehicle model from the Excel Look up tables

% Load the entire look-up table
VDatabase = sm_car_import_vehicle_data(0,1);

% needed to avoid an error in the structure creation phase
VDatabase.Linkage = [];

%% Generate the "Vehicle" struct 
vehcfg_set = {
    'Aero',         'Truck_Amandla',                     '';...
    'Body',         'Truck_Amandla_3Axle',               '';...
    'BodyGeometry', 'CAD_Truck_Amandla',                 '';...
    'Passenger',    'None',                              '';...
    'Power',        'Ideal_A2_default',                  '';...
    'Brakes',       'Axle3_PedalAbstract_DiscDiscDisc_Truck_Amandla_Axle3',    '';...
    'Springs',      'Axle3_None',                        'None_None_None';...
    'Dampers',      'Axle3_None',                        'None_None_None';...
    'Susp',         'Simple15DOF_Truck_Amandla_A1',      'SuspA1';
    'Susp',         'Simple15DOF_Truck_Amandla_A2',      'SuspA2';
    'Susp',         'Simple15DOF_Truck_Amandla_A3',      'SuspA3';
    'Steer',        'Ackermann_Amandla_A1',              'SuspA1';...
    'Steer',        'None_default',                      'SuspA2';...
    'Steer',        'None_default',                      'SuspA3';...
    'DriverHuman',  'Truck_Amandla',                     'SuspA1';...
    'AntiRollBar',  'None',                              'SuspA1';...
    'AntiRollBar',  'None',                              'SuspA2';...
    'AntiRollBar',  'None',                              'SuspA3';...
    'Tire',         'MFMbody_CAD_430_50R38',             'TireA1';
    'Tire',         'MFMbody_2x_CAD_430_50R38',          'TireA2';
    'Tire',         'MFMbody_2x_CAD_430_50R38',          'TireA3';
    'TireDyn',      'steady',                            'TireA1';
    'TireDyn',      'steady',                            'TireA2';
    'TireDyn',      'steady',                            'TireA3';
    'Driveline',    'A11D_A21D3_A31D_TA3',               ''};

assignin('base','vehcfg_set',vehcfg_set); % For debugging

% Assemble vehicle
Vehicle = sm_car_vehcfg_assemble_vehicle(vehcfg_set);
Vehicle.config = 'Amandla3Axle_15DOF_MFEval_steady_6x2';


%% Create the trailer model
% needed to avoid an error in the structure creation phase
VDatabase.Linkage = [];

vehcfg_set = {
    'Aero',         'Trailer_Kumanzi',                   '';...
    'Body',         'Trailer_Kumanzi',                   '';...
    'BodyGeometry', 'CAD_Trailer_Kumanzi',               '';...
    'BodyLoad',     'None',                              '';...
    'Passenger',    'None',                              '';...
    'Power',        'None',                              '';...
    'Brakes',       'Axle2_None',                        '';...
    'Springs',      'Axle2_None',                        'None_None';...
    'Dampers',      'Axle2_None',                        'None_None';...
    'Susp',         'Simple15DOF_Trailer_Kumanzi_A1',    'SuspA1';
    'Susp',         'Simple15DOF_Trailer_Kumanzi_A2',    'SuspA2';
    'Steer',        'None_default',                      'SuspA1';...
    'Steer',        'None_default',                      'SuspA2';...
    'DriverHuman',  'None',                              'SuspA1';...
    'AntiRollBar',  'None',                              'SuspA1';...
    'AntiRollBar',  'None',                              'SuspA2';...
    'Tire',         'MFMbody_2x_CAD_430_50R38',          'TireA1';
    'Tire',         'MFMbody_2x_CAD_430_50R38',          'TireA2';
    'TireDyn',      'steady',                            'TireA1';
    'TireDyn',      'steady',                            'TireA2';
    'Driveline',    'Axle2_None',                         ''};

assignin('base','vehcfg_set',vehcfg_set); % For debugging

Trailer = sm_car_vehcfg_assemble_vehicle(vehcfg_set);
Trailer.config = 'Kumanzi_15DOF_MFMbody_steady_noLoad';