% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Aug-2024 09:11:49
%  MATLAB version: 24.1.0.2628055 (R2024a) Update 4
% -------------------------------------------------------------------
                                          

Init_Trailer = struct;
Init_Trailer.Instance = 'Trailer_Kumanzi';
Init_Trailer.Type = 'Flat';
Init_Trailer.Chassis = struct;
Init_Trailer.Chassis.aChassis = struct;
Init_Trailer.Chassis.aChassis.Units = 'rad';
Init_Trailer.Chassis.aChassis.Value = ...
  [0 0 0];
Init_Trailer.Chassis.aChassis.Comments = ...
  'Roll-Pitch-Yaw. Not used in assembly with car.';
Init_Trailer.Chassis.vChassis = struct;
Init_Trailer.Chassis.vChassis.Units = 'm/s';
Init_Trailer.Chassis.vChassis.Value = ...
  [1 0 0];
Init_Trailer.Chassis.vChassis.Comments = ...
  'Not used in assembly with car.';
Init_Trailer.Chassis.sChassis = struct;
Init_Trailer.Chassis.sChassis.Units = 'm';
Init_Trailer.Chassis.sChassis.Value = ...
  [5 0 0];
Init_Trailer.Chassis.sChassis.Comments = ...
  'Not used in assembly with car.';
Init_Trailer.Axle1 = struct;
Init_Trailer.Axle1.nWheel = struct;
Init_Trailer.Axle1.nWheel.Units = 'rad/s';
Init_Trailer.Axle1.nWheel.Comments = 'Values are [left right]';
Init_Trailer.Axle1.nWheel.Value = [1.4857 1.4857 0.6731];
Init_Trailer.Axle2 = struct;
Init_Trailer.Axle2.nWheel = struct;
Init_Trailer.Axle2.nWheel.Units = 'rad/s';
Init_Trailer.Axle2.nWheel.Comments = 'Values are [left right]';
Init_Trailer.Axle2.nWheel.Value = [1.4857 1.4857 0.6731];

