stages:
  - testModels

Example1:
  stage: testModels
  tags: 
    - on-prem
  script:
    - mw -using BR2024ad matlab -batch "project = openProject('SVT_Truck.prj'); ci.testExmp1;"

Example2:
  stage: testModels
  tags: 
    - on-prem
  script:
    - mw -using BR2024ad matlab -batch "project = openProject('SVT_Truck.prj'); ci.testExmp2;"

Example3:
  stage: testModels
  tags: 
    - on-prem
  script:
    - mw -using BR2024ad matlab -batch "project = openProject('SVT_Truck.prj'); ci.testExmp3;"
