% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Aug-2024 09:11:49
%  MATLAB version: 24.1.0.2628055 (R2024a) Update 4
% -------------------------------------------------------------------
                                       

Maneuver = struct;
Maneuver.Brake = struct;
Maneuver.Brake.t = struct;
Maneuver.Brake.t.Units = 'sec';
Maneuver.Brake.t.Comments = '';
Maneuver.Brake.t.Value = [0 21 21.2 190 191 200];
Maneuver.Brake.rPedal = struct;
Maneuver.Brake.rPedal.Units = '0-1';
Maneuver.Brake.rPedal.Comments = '';
Maneuver.Brake.rPedal.Value = [0 0 1 1 0 0];
Maneuver.Steer = struct;
Maneuver.Steer.t = struct;
Maneuver.Steer.t.Units = 'sec';
Maneuver.Steer.t.Comments = '';
Maneuver.Steer.t.Value = [0 21 21.2 100 150 200];
Maneuver.Steer.aWheel = struct;
Maneuver.Steer.aWheel.Units = 'rad';
Maneuver.Steer.aWheel.Comments = '';
Maneuver.Steer.aWheel.Value = [0 0 0 0 0 0];
Maneuver.Accel = struct;
Maneuver.Accel.t = struct;
Maneuver.Accel.t.Units = 'sec';
Maneuver.Accel.t.Comments = '';
Maneuver.Accel.t.Value = [0 1 1.2 20 20.2 200];
Maneuver.Accel.rPedal = struct;
Maneuver.Accel.rPedal.Units = '0-1';
Maneuver.Accel.rPedal.Comments = '';
Maneuver.Accel.rPedal.Value = [0 0 1 1 0 0];
Maneuver.Type = 'WOT_Braking';
Maneuver.Instance = 'Truck_Amandla';

