% function [Driver, Maneuver] = paramDriver(Vehicle)


% --- Longitudinal Parameters ---
Driver.Long.mVehicle.Value         = 1500;
Driver.Long.mVehicle.Units         = 'kg';
Driver.Long.mVehicle.Comments      = 'Vehicle Mass';

Driver.Long.FTractive.Value        = 17297;
Driver.Long.FTractive.Units        = 'N';
Driver.Long.FTractive.Comments     = 'Max vehicle tractive force';

Driver.Long.tDriver.Value          = 0.1;
Driver.Long.tDriver.Units          = 's';
Driver.Long.tDriver.Comments       = 'Driver time filter constant';

Driver.Long.xPreview.Value         = 20;
Driver.Long.xPreview.Units         = 'm';
Driver.Long.xPreview.Comments      = 'Driver Preview distance';

Driver.Long.NDragRoll.Value        = 200;
Driver.Long.NDragRoll.Units        = 'N';
Driver.Long.NDragRoll.Comments     = '';

Driver.Long.NDragRollDriveline.Value = 2.5;
Driver.Long.NDragRollDriveline.Units = 'N*s/m';
Driver.Long.NDragRollDriveline.Comments = '';

Driver.Long.NDragAero.Value        = 0;
Driver.Long.NDragAero.Units        = 'N*s^2/m^2';
Driver.Long.NDragAero.Comments     = '';

Driver.Long.gGravity.Value         = 9.80665;
Driver.Long.gGravity.Units         = 'm/s^2';
Driver.Long.gGravity.Comments      = '';

Driver.Long.fAccelCutoff.Value     = 31.4159265;
Driver.Long.fAccelCutoff.Units     = '1/s';
Driver.Long.fAccelCutoff.Comments  = '';

Driver.Long.fBrakeCutoff.Value     = 31.4159265;
Driver.Long.fBrakeCutoff.Units     = '1/s';
Driver.Long.fBrakeCutoff.Comments  = '';

Driver.Long.FFLookahead.Value      = 0.5;
Driver.Long.FFLookahead.Units      = 's';
Driver.Long.FFLookahead.Comments   = '';

Driver.Long.NRollingResistance.Value    = 0.01;
Driver.Long.NRollingResistance.Units    = '1';
Driver.Long.NRollingResistance.Comments = '';

Driver.Long.NRoadFriction.Value    = 0.9;
Driver.Long.NRoadFriction.Units    = '1';
Driver.Long.NRoadFriction.Comments = '';

Driver.Long.Kp.Value               = 0.3125;
Driver.Long.Kp.Units               = '1';
Driver.Long.Kp.Comments            = '';

Driver.Long.Ki.Value               = 0.0391;
Driver.Long.Ki.Units               = '1';
Driver.Long.Ki.Comments            = '';

Driver.Long.gMaxAccel.Value        = 5;
Driver.Long.gMaxAccel.Units        = 'm/s^2';
Driver.Long.gMaxAccel.Comments     = '';

Driver.Long.gMaxDecel.Value        = -10;
Driver.Long.gMaxDecel.Units        = 'm/s^2';
Driver.Long.gMaxDecel.Comments     = '';

% --- Lateral Parameters ---
Driver.Lateral.xWheelbase.Value    = Vehicle.Chassis.Body.xWheelbase.Value;
Driver.Lateral.xWheelbase.Units    = 'm';
Driver.Lateral.xWheelbase.Comments = 'Wheelbase of the vehicle';

Driver.Lateral.aMaxSteer.Value     = 35;
Driver.Lateral.aMaxSteer.Units     = 'deg';
Driver.Lateral.aMaxSteer.Comments  = '';

Driver.Lateral.fSteerCutoff        = struct;
Driver.Lateral.fSteerCutoff.Value  = 314.159265;
Driver.Lateral.fSteerCutoff.Units  = 'rad/s';

% --- Controller Settings ---
Driver.Lateral.Stanley             = struct;
Driver.Lateral.Stanley.NForward.Value = 1;
Driver.Lateral.Stanley.NReverse.Value = 0.25;
Driver.Lateral.Stanley.Units       = '';
Driver.Lateral.Stanley.Comments    = '';

Driver.Lateral.Pursuit             = struct;
Driver.Lateral.Pursuit.kLookahead.Value      = 3;
Driver.Lateral.Pursuit.xLookaheadMin.Value   = 0.5;
Driver.Lateral.Pursuit.xLookaheadMin.Units   = 'm';
Driver.Lateral.Pursuit.xLookaheadMax.Value   = 20;
Driver.Lateral.Pursuit.xLookaheadMax.Units   = 'm';
Driver.Lateral.Pursuit.nWeightHeadingErr.Value = 0.5;
Driver.Lateral.Pursuit.Units       = '';
Driver.Lateral.Pursuit.Comments    = '';

Driver.Lateral.class.Value         = 'Stanley';
Driver.Lateral.class.Units         = '';
Driver.Lateral.class.Comments      = '';

% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Dec-2025 15:59:35
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------

% --- Constraints and Gains ---
Maneuver.xMaxLat.Value              = 5;
Maneuver.xMaxLat.Units              = 'm';
Maneuver.xMaxLat.Comments           = 'Max lateral allowed distance in m';

Maneuver.vMinTarget.Value           = 0;
Maneuver.vMinTarget.Units           = 'm/s';
Maneuver.vMinTarget.Comments        = 'Minimum target velocity';

Maneuver.vGain.Value                = 1;
Maneuver.vGain.Units                = '';
Maneuver.vGain.Comments             = 'Scales target speed Trajectory vx';

Maneuver.xMax.Value                 = Inf;
Maneuver.xMax.Units                 = 'm';
Maneuver.xMax.Comments              = 'Stop test when vehicle has reached this distance';

% --- Preview Settings ---
Maneuver.nPreviewPoints.Value       = 5;
Maneuver.nPreviewPoints.Units       = '';
Maneuver.nPreviewPoints.Comments    = 'For Pure Pursuit Driver';

Maneuver.xPreview.x.Value           = [2.5 3 10];
Maneuver.xPreview.x.Units           = 'm';
Maneuver.xPreview.v.Value           = [0 5 20];
Maneuver.xPreview.v.Units           = 'm/s';

% end
